platform :ios, ’10.0’
use_frameworks!

# -> Definitions

def networking
	pod 'Alamofire', '~> 4.0’
end


def utils
    pod 'youtube-ios-player-helper', '~> 0.1.4'
    pod 'SDWebImage', '~>3.7'
end

# -> Targets

target 'AniList' do
	networking
	utils
end
